apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-module-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tour-pod
  template:
    metadata:
      labels:
        app: tour-pod
    spec:
      containers:
        - name: tour-contr
          image: public.ecr.aws/s8j2k2x6/tour
          # image: 557571305961.dkr.ecr.us-east-1.amazonaws.com/tour:latest
          volumeMounts: #mount the volume from POD into the container
            - name: config-env-vol
              mountPath: /app/env
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tour-global-secret
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tour-global-secret
                  key: JWT_SECRET_KEY
            - name: RZPAY_KEYID
              valueFrom:
                secretKeyRef:
                  name: tour-global-secret
                  key: RZPAY_KEYID
            - name: RZPAY_KEYSECRET
              valueFrom:
                secretKeyRef:
                  name: tour-global-secret
                  key: RZPAY_KEYSECRET
            - name: git_token
              valueFrom:
                secretKeyRef:
                  name: tour-global-secret
                  key: git_token

      volumes: #mount a volume to the POD
        - name: config-env-vol
          configMap:
            name: tour-svc-config
---
apiVersion: v1
kind: Service
metadata:
  name: tour-srv
spec:
  selector:
    app: tour-pod
  ports:
    - name: tour-port
      protocol: TCP
      port: 5000
      targetPort: 5000
